### ISSUE TITLE
Configure iDRAC Users Add or change password is failing with error "Module failure"

### ISSUE THREAD

**Issue by wilfredm91** [anupamaloke/Dell-EMC-Ansible-Modules-for-iDRAC#20]
![config_idrac_users](https://user-images.githubusercontent.com/31649308/31532702-7f19bb9c-b00c-11e7-9eb9-026691923b38.jpg)

**Comment by anupamaloke** [comment]
enum34 was not installed. Error was not observed after installation of enum34 python module.
