### ISSUE TITLE
Configure Boot Mode failing with an "Error: isinstance() arg 2 must be a class, type, or tuple of classes and types"

### ISSUE THREAD

**Issue by wilfredm91** [anupamaloke/Dell-EMC-Ansible-Modules-for-iDRAC#21]
![bootmode](https://user-images.githubusercontent.com/31649308/31532780-e7421214-b00c-11e7-8bb2-89bad1412e78.JPG)

**Comment by anupamaloke** [comment]
'enum34' module was not installed. No issue seen after installation of enum34 python module.
